query Languages ($id: String) {
	viewer {
    id
    repositories(first: 100) {
      edges {
        node {
          primaryLanguage {
            name
            color
          }
          defaultBranchRef {
            target {
							... on Commit {
                history(first: 0 author: {id: $id}) {
                  totalCount
                }
              }
            }
          }
        }
      }
    }
  }
}
